#!/bin/bash

commit=`
diff -u <(git rev-list --first-parent HEAD) \
             <(git rev-list --first-parent master) | \
     sed -ne 's/^ //p' | head -1
`
commitMsg=$1

if [ -z "$commitMsg" ]
then
    echo "Invalid commit message.  Make sure string is not empty"
else
    count=`git rev-list $commit.. --count`
    git reset --soft "$commit" > /dev/null
    git commit -m "$commitMsg" > /dev/null
    echo
    echo "Squashed $count commit(s) back to $commit"
fi

exit 0
